server:
  port: 8762
spring:
  application:
    name: ccs-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ccs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: com.yidiandian.config.EncodingMysqlConfig  #配置类全路径
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yidiandian.entity
  redis:
    host: localhost
    port: 6379
    password:
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500


eureka:
  instance:
    appname: ccs-server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/